# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (ignore scripts to avoid running prepare automatically)
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any required port if needed (not strictly necessary for stdio-based MCP)

# Command to run the MCP server
CMD [ "node", "build/index.js" ]
